config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :users, except: [:show] do
    member do
      get 'activity'
      get 'profile'
      get 'achievements'
      get 'teams'
    end
  end
  resources :achievements
  resources :achievements_users, only: [:new, :create, :destroy]
  resources :teams
  resources :notifications, only: [:index]
  namespace :leaderboards do
    resources :users, only: :index do
      get 'fetch', on: :collection
    end
  end

  get 'me', to: 'users#me'
  get '/u(sers)/:nickname', to: 'users#show', as: :show_user, constraints: { nickname: %r{[^\/]+(?=\.html\z|\.json\z)|[^\/]+} }

  resources :charts, only: [] do
    collection do
      get 'points_per_day'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web, at: 'jobs'
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notificable, polymorphic: true

  after_create_commit { NotificationBroadcastJob.perform_later(id) }

  scope :seen, -> { where(seen: true) }
  scope :unseen, -> { where(seen: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  respond_to :html
  load_and_authorize_resource

  def index
    @notifications = current_user.notifications.active.order(created_at: :desc)
    @notifications.update_all(seen: true, updated_at: Time.current)
    @notifications = @notifications.paginate(page: params[:page], per_page: 10)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notificable_link(notification)
    notificable = notification.notificable
    path = "#{notificable.class.name.downcase}_path"
    link_to(notificable.name, send(path, notificable))
  end
end

app/views/notifications/_counter.html.haml
= link_to notifications_path do
  %i.fa.fa-bell.fa-lg
  - if counter > 0
    %span.label.label-success= counter

app/views/notifications/_notification.html.haml
%tr.notification
  %td
    .small #{notification.created_at.to_formatted_s(:short)}
    #{notification.message} #{notificable_link(notification)}

app/views/notifications/index.html.haml
%h1 Notification Center
%table.table.pretty#notifications
  %tbody= render @notifications
%p= will_paginate @notifications, renderer: BootstrapPagination::Rails