config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :users, except: [:show] do
    member do
      get 'activity'
      get 'profile'
      get 'achievements'
      get 'teams'
    end
  end
  resources :achievements
  resources :achievements_users, only: [:new, :create, :destroy]
  resources :teams
  resources :notifications, only: [:index]
  namespace :leaderboards do
    resources :users, only: :index do
      get 'fetch', on: :collection
    end
  end

  get 'me', to: 'users#me'
  get '/u(sers)/:nickname', to: 'users#show', as: :show_user, constraints: { nickname: %r{[^\/]+(?=\.html\z|\.json\z)|[^\/]+} }

  resources :charts, only: [] do
    collection do
      get 'points_per_day'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web, at: 'jobs'
end

app/models/user.rb
class User < ApplicationRecord
  include Rankable
  devise :invitable, :database_authenticatable, :registerable, :recoverable,
         :rememberable, :trackable, :validatable, :encryptable, :omniauthable

  has_many :achievements_users, dependent: :destroy
  has_many :achievements, through: :achievements_users
  has_many :teams_users, dependent: :destroy
  has_many :teams, through: :teams_users
  has_many :notifications

  validates :first_name, :last_name, presence: true

  before_save :level_up, if: proc { |a| a.experience_changed? || a.new_record? }
  before_create :assign_nickname

  alias_attribute :points, :experience

  def name
    "#{first_name} #{last_name}"
  end

  def progress_percentage
    next_exp = experience_for_next_level
    previous_exp = experience_for_current_level
    percentage = (experience - previous_exp) / (next_exp - previous_exp) * 100
    return 0 if percentage == 100
    percentage.round(2)
  end

  def experience_for_current_level
    LevelConverter.new(self).reverse
  end

  def experience_for_next_level
    LevelConverter.new(self, next_level: true).reverse
  end

  def notifications_count
    notifications.active.unseen.count
  end

  private

  def level_up
    self.level = LevelConverter.new(self).convert.to_i
  end

  def assign_nickname
    self.nickname ||= "#{first_name.downcase}.#{last_name.downcase}"
    number = 1
    while User.where(nickname: self.nickname).exists?
      self.nickname = "#{nickname}.#{number}"
      number += 1
    end
  end
end

app/controllers/leaderboards/users_controller.rb
module Leaderboards
  class UsersController < BaseController
    respond_to :html

    def index; end

    def fetch
      @users_with_scores = Users.call(leaderboard_params)
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
  load_and_authorize_resource
  skip_authorize_resource only: [:activity, :profile, :achievements, :teams]
  before_action :set_user_profile, only: [:activity, :profile, :achievements, :teams]

  def me
    redirect_to user_path(current_user.nickname)
  end

  def show
    @user = User.active.find_by!(nickname: params[:nickname])
    respond_with(@user)
  end

  def activity
    respond_to do |format|
      format.js
    end
  end

  def profile
    respond_to do |format|
      format.js
    end
  end

  def achievements
    respond_to do |format|
      format.js
    end
  end

  def teams
    respond_to do |format|
      format.js
    end
  end

  private

  def set_user_profile
    user = User.find(params[:id])
    @user_profile = UserProfile.new(user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def level_progressbar(user)
    capture_haml do
      haml_tag :div, class: 'progress' do
        haml_tag :div, progressbar_options(user) do
          haml_concat experience_ratio(user)
        end
      end
    end
  end

  def progressbar_options(user)
    {
      class: 'progress-bar progress-bar-success',
      role: 'progressbar',
      aria_valuenow: user.progress_percentage,
      aria_valuemin: 0,
      aria_valuemax: 100,
      style: "width: #{user.progress_percentage}%"
    }
  end

  def experience_ratio(user)
    "#{user.experience}/#{user.experience_for_next_level.to_i}"
  end
end

app/views/users/_achievements.html.haml
.panel.panel-info
  .panel-heading
    %h3.panel-title
      Achievements
  .panel-body
    .btn-group.btn-group-justified{ role: 'group'}
      .btn.btn-default.nocursor
        %i.fa.fa-trophy{ style: 'color: gold' }
        ×#{user.achievements.gold.count}
      .btn.btn-default.nocursor
        %i.fa.fa-trophy{ style: 'color: silver' }
        ×#{user.achievements.silver.count}
      .btn.btn-default.nocursor
        %i.fa.fa-trophy{ style: 'color: saddlebrown' }
        ×#{user.achievements.bronze.count}
    %br
    - user.grouped_achievements.each_slice(3) do |achievements|
      .row
        - achievements.each do |achievement, count|
          .col-md-offset-1.col-md-3
            = link_to achievement_path(achievement) do
              %p.text-center
                %i.fa.fa-trophy.fa-5x{ style: icon_style(achievement) }
              %p.text-center #{achievement.name} ×#{count}

app/views/users/_activity.html.haml
.panel.panel-success
  .panel-heading
    %h3.panel-title Expierience
  .panel-body= level_progressbar(user)
.panel.panel-info
  .panel-heading
    %h3.panel-title Achievements
  .panel-body
    .btn-group.btn-group-justified{ role: 'group'}
      .btn.btn-default.nocursor
        %i.fa.fa-trophy{ style: 'color: gold' }
        ×#{user.achievements.gold.count}
      .btn.btn-default.nocursor
        %i.fa.fa-trophy{ style: 'color: silver' }
        ×#{user.achievements.silver.count}
      .btn.btn-default.nocursor
        %i.fa.fa-trophy{ style: 'color: saddlebrown' }
        ×#{user.achievements.bronze.count}

    %table.table
      %thead
        %tr
          %th Recent
      %tbody
        - user.recent_achievements.each do |au|
          %tr
            %td
              = au.achievement.name
              %i.fa.fa-trophy{ style: icon_style(au.achievement) }
.panel.panel-default
  .panel-heading
    %h3.panel-title Experience gain per day
  .panel-body= area_chart(points_per_day_charts_path(user_id: user.id), label: 'Experience')

app/views/users/_profile.html.haml
.panel.panel-success
  .panel-heading
    %h3.panel-title
      = user.first_name
      - if user.position
        \- #{user.position}
      - if user.monthly_top.present?
        .pull-right Top #{user.monthly_top}% this month
  .panel-body
    - if user.about_me
      %p= user.about_me
      %hr
    %ul.blank
      - if user.location
        %li
          %i.fa.fa-map-marker
          = user.location
      %li
        %i.fa.fa-history
        Member for #{time_ago_in_words(user.created_at)}
      - if user.last_seen_at
        %li
          %i.fa.fa-eye
          Last seen #{time_ago_in_words(user.last_seen_at)} ago
      - if user.website
        %li
          %i.fa.fa-link
          = link_to user.website, user.website_link
      - if user.twitter
        %li
          %i.fa.fa-twitter
          = link_to "@#{user.twitter}", user.twitter_link
      - if user.github
        %li
          %i.fa.fa-github
          = link_to user.github, user.github_link

app/views/users/_sidebar.html.haml
.profile-userpic= image_tag('default_profile.jpg')
.profile-usertitle
  .profile-usertitle-name= @user.name
  .profile-usertitle-job= @user.nickname
.profile-userbuttons
  .btn.btn-success.btn-sm Level #{@user.level}
.profile-usermenu
  %ul.nav
    %li.active
      = link_to activity_user_path(@user), remote: true do
        %i.fa.fa-line-chart.fa-fw
        Activity
    %li
      = link_to profile_user_path(@user), remote: true do
        %i.fa.fa-user.fa-fw
        Profile
    %li
      = link_to achievements_user_path(@user), remote: true do
        %i.fa.fa-trophy.fa-fw
        Achievements
    %li
      = link_to teams_user_path(@user), remote: true do
        %i.fa.fa-group.fa-fw
        Teams

app/views/users/_teams.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title Teams
  .panel-body
    %ul.list-group
      - user.teams.each do |team|
        %li.list-group-item= link_to team.name, team_path(team)

app/views/users/achievements.js.erb
$('#content').html("<%= escape_javascript(render(partial: 'achievements', locals: { user: @user_profile })) %>");

app/views/users/activity.js.erb
$('#content').html("<%= escape_javascript(render(partial: 'activity', locals: { user: @user_profile })) %>");

app/views/users/profile.js.erb
$('#content').html("<%= escape_javascript(render(partial: 'profile', locals: { user: @user_profile })) %>");

app/views/users/show.html.haml
.row.profile
  .col-md-3
    #sidebar.profile-sidebar= render('sidebar')
  .col-md-9
    #content.profile-content

app/views/users/teams.js.erb
$('#content').html("<%= escape_javascript(render(partial: 'teams', locals: { user: @user_profile })) %>");