config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :users, except: [:show] do
    member do
      get 'activity'
      get 'profile'
      get 'achievements'
      get 'teams'
    end
  end
  resources :achievements
  resources :achievements_users, only: [:new, :create, :destroy]
  resources :teams
  resources :notifications, only: [:index]
  namespace :leaderboards do
    resources :users, only: :index do
      get 'fetch', on: :collection
    end
  end

  get 'me', to: 'users#me'
  get '/u(sers)/:nickname', to: 'users#show', as: :show_user, constraints: { nickname: %r{[^\/]+(?=\.html\z|\.json\z)|[^\/]+} }

  resources :charts, only: [] do
    collection do
      get 'points_per_day'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web, at: 'jobs'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  RANKS = {
    'bronze' => 20,
    'silver' => 40,
    'gold' => 120
  }.freeze

  has_many :achievements_users, dependent: :destroy
  has_many :users, through: :achievements_users
  has_many :notifications, as: :notificable

  scope :gold, -> { where(rank: 'gold') }
  scope :silver, -> { where(rank: 'silver') }
  scope :bronze, -> { where(rank: 'bronze') }

  validates :name, :rank, :description, presence: true
  validates :name, :rank, :rewards, length: { maximum: 255 }
  validates :points,
            numericality: { only_integer: true, greater_than: 0 }, allow_nil: true
  validates :rank, inclusion: { in: RANKS.keys }

  before_validation :assign_points, if: proc { |a| a.rank_changed? || a.new_record? }

  private

  def assign_points
    self.points = RANKS[rank]
  end
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  respond_to :html
  load_and_authorize_resource

  def index
    @achievements = Achievement.active.order(:created_at)
                               .paginate(page: params[:page], per_page: 10)
    respond_with(@achievements)
  end

  def show
    @achievement = Achievement.active.find(params[:id])
    respond_with(@achievement)
  end

  def new
    @achievement = Achievement.new
    respond_with(@achievement)
  end

  def edit
    @achievement = Achievement.active.find(params[:id])
    respond_with(@achievement)
  end

  def create
    @achievement = Achievement.new(achievement_params)
    if @achievement.save
      flash[:notice] = 'Achievement saved!'
      respond_with(@achievement)
    else
      render action: :new
    end
  end

  def update
    @achievement = Achievement.active.find(params[:id])
    @achievement.update(achievement_params)
    respond_with(@achievement)
  end

  def destroy
    @achievement = Achievement.active.find(params[:id])
    @achievement.destroy
    respond_with(@achievement)
  end

  private

  def achievement_params
    params.require(:achievement)
          .permit(:name, :description, :rank, :rewards, :starts_at, :ends_at)
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
  def icon_style(achievement)
    "color: #{icon_color(achievement)}"
  end

  def icon_color(achievement)
    {
      'bronze' => 'saddlebrown',
      'silver' => 'silver',
      'gold' => 'gold'
    }.fetch(achievement.rank)
  end
end

app/views/achievements/_form.html.haml
.row
  .col-md-6.col-md-offset-3
    = simple_form_for @achievement do |f|
      = f.error_notification
      .form-inputs
        = f.input :name, autofocus: true, required: true
        = f.input :description, required: true
        = f.input :rank, collection: Achievement::RANKS.keys, include_blank: false
        = f.input :rewards
      .form-actions
        = f.button :submit, 'Save changes'

app/views/achievements/edit.html.haml
%h1 Editing Achievement

= render 'form'

= link_to 'Show', @achievement
|
= link_to 'Back', achievements_path

app/views/achievements/index.html.haml
%h1 Listing achievements

%table.table.table-striped.pretty
  %thead
    %tr
      %th Name
      %th Points
      %th Rewards
      %th{ colspan: 3 }
  %tbody
    - @achievements.each do |achievement|
      %tr
        %td
          %b= achievement.name
          %p.small
            = truncate(achievement.description, length: 80, separator: ' ')
        %td
          = achievement.points
          %i.fa.fa-trophy{ style: icon_style(achievement) }
        %td= achievement.rewards
        %td= link_to 'Show', achievement
        %td= link_to 'Edit', edit_achievement_path(achievement) if can? :update, achievement
        %td= link_to 'Remove', achievement, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, achievement

%p= will_paginate @achievements, renderer: BootstrapPagination::Rails

= link_to 'New achievement', new_achievement_path, class: 'btn btn-primary' if can? :create, Achievement

app/views/achievements/new.html.haml
%h1 New Achievement

= render 'form'

= link_to 'Back', achievements_path

app/views/achievements/show.html.haml
.row
  .col-md-12
    %h2
      %i.fa.fa-trophy{ style: icon_style(@achievement) }
      = @achievement.name
    %h3= @achievement.description
    %p
      Rewards:
      = @achievement.rewards

= link_to 'Back', achievements_path