config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources :users, except: [:show] do
    member do
      get 'activity'
      get 'profile'
      get 'achievements'
      get 'teams'
    end
  end
  resources :achievements
  resources :achievements_users, only: [:new, :create, :destroy]
  resources :teams
  resources :notifications, only: [:index]
  namespace :leaderboards do
    resources :users, only: :index do
      get 'fetch', on: :collection
    end
  end

  get 'me', to: 'users#me'
  get '/u(sers)/:nickname', to: 'users#show', as: :show_user, constraints: { nickname: %r{[^\/]+(?=\.html\z|\.json\z)|[^\/]+} }

  resources :charts, only: [] do
    collection do
      get 'points_per_day'
    end
  end

  mount ActionCable.server => '/cable'
  mount Sidekiq::Web, at: 'jobs'
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{ role: 'navigation' }
  .container-fluid
    .navbar-header
      %button.navbar-toggle{ 'data-target' => '#bs-example-navbar-collapse-1', 'data-toggle' => 'collapse', type: 'button' }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li= link_to 'Leaderboard', leaderboards_users_path
          %li= link_to 'Achievements', achievements_path
          %li= link_to 'Teams', teams_path
          - if current_user.admin?
            %li= link_to 'Grant an achievement', new_achievements_user_path
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li#notifications_counter= render 'notifications/counter', counter: current_user.notifications_count
        %li.dropdown
          - if user_signed_in?
            %a.dropdown-toggle{ 'data-toggle' => 'dropdown', href: '#' }
              Account
              %span.caret
            %ul.dropdown-menu{ role: 'menu' }
              %li= link_to 'Profile', me_path
              %li= link_to 'Settings', edit_user_registration_path
              %li.divider
              %li= link_to 'Log out', destroy_user_session_path, method: :delete
          - else
            %li= link_to 'Log in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Gamification
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://www.gstatic.com/charts/loader.js'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{ class: "#{controller_name} #{action_name}" }
    %container
      = render 'layouts/navbar'
      .container
        = flash_messages
        = yield